### ISSUE TITLE
Use less general tags for styling

### ISSUE THREAD

**Issue by TheByteSizeDev** [dhollifield/daily-journal#3]
Overall you did an absolutely fantastic job! Next time I'd just say to try to challenge yourself to use less general tags to style and instead use classes. You can get yourself in a lot of trouble doing that when you start to have more than on `<h3>` tags.

https://github.com/dhollifield/daily-journal/blob/702ae3d285bcdee6aa7d4be72f22eb041745329b/main.css#L10-L14

**Comment by dhollifield** [comment]
Gave H3 a  class
